name: DockerHub CI

on:
  push:
    tags:
      - 'latest'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: maxrohleder/maxserver:latest
  deployment:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ secrets.UPDATE_TRIGGER_URL }}
        method: 'POST'
        data: user=${{ secrets.STRATO_USER }} & secret=${{ secrets.STRATO_PWD }}
