name: Deployment Strato Dockerhub CI

on:
  push:
    tags:
      - 'latest'
      
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: maxrohleder/maxserver:latest
          
  trigger-deployment:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - 
        name: run latest image from dockerhub 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker stop spruzserver
            docker rm spruzserver
            docker rmi maxrohleder/maxserver:latest
            docker run -dp 80:80 --name spruzserver maxrohleder/maxserver:latest
